// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aira.Persistence.Aira.Models
{
    public partial class JobOfferMain
    {
        public Guid JobOfferId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDescription { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string SalaryType { get; set; }
        public decimal? SalaryFrom { get; set; }
        public decimal? SalaryTo { get; set; }
        public DateTime? SalaryTime { get; set; }
        public string LocationCountry { get; set; }
        public string LocationCity { get; set; }
        public string LocationVoivodeship { get; set; }
        public string LocationDetails { get; set; }
        public string WorkingModel { get; set; }
        public string ContractType { get; set; }
        public string WorkingTime { get; set; }
        public string RecruitmentMode { get; set; }
        public byte? VacancyNumber { get; set; }
    }
}