// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aira.Persistence.Aira.Models
{
    public partial class JobOfferContentEducation
    {
        public string EducationLevel { get; set; }
        public string EducationStudiesName { get; set; }
        public string EducationStudiesStage { get; set; }
        public string CertificatesName { get; set; }
        public string CertificatesStage { get; set; }
        public string CertificatesQualification { get; set; }
        public string ExperiencePosition { get; set; }
        public string ExperienceField { get; set; }
        public string ExperienceTime { get; set; }
        public Guid JobOfferId { get; set; }
    }
}