// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aira.Persistence.Aira.Models
{
    public partial class JobOfferContent
    {
        public Guid JobOfferId { get; set; }
        public string Responsibilities { get; set; }
        public string Requirements { get; set; }
        public string Benefits { get; set; }
        public string OurOffer { get; set; }
    }
}