// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aira.Persistence.Aira.Models
{
    public partial class JobOfferAdditionalInfo
    {
        public string DataProcessing { get; set; }
        public string MediumType { get; set; }
        public string CvFormat { get; set; }
        public DateTime? EndDate { get; set; }
        public string ContactInfo { get; set; }
        public Guid JobOfferId { get; set; }
    }
}